version: '3.8'
services:
  crud-app:
    container_name: crud-app
    image: app
    build: .
    depends_on:
      crud-db:
        condition: service_healthy
    ports:
      - "8081:8081"
    networks:
      - crud

  crud-db:
    container_name: crud-db
    image: postgres
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 2s
      retries: 3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=crudappdb
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./pgdata:/var/lib/postgresql
    networks:
      - crud

networks:
  crud:
    driver: bridge
